[package]
name = "locus-py"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lib]
name = "locus"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py310"] }
numpy = "0.23"
locus-core = { path = "../locus-core" }
bumpalo = "3.16"
tracing = "0.1.44"
[lints]
workspace = true

