allow-branch = ["main"]
sign-commit = false
sign-tag = false
push = true
publish = false

shared-version = true
tag-name = "v{{version}}"

[[pre-release-replacements]]
file = "../../pyproject.toml"
search = "^version = \".*\""
replace = "version = \"{{version}}\""
min = 0
